#!/home/rsv/Desktop/ansible/myansible/bin/ansible-playbook
- name: This is Overview of Ansible Debug Module
  hosts: all
  remote_user: ubuntu
  become: 'yes'
  become_user: root

  tasks:
    - name: Task for debug Module massage
      debug:
        msg: "This is printing"

    - name: Task for debug Module massage more than two lines
      debug:
        msg:
          - "this is line1"
          - "this is line2"
  
    - name: Task for debug Module printing varibles
      debug:
        msg: 
          - "Host IP is - {{ inventory_hostname }}"
          - Host IP is - {{ inventory_hostname }}
          - System {{ inventory_hostname }} has gateway {{ ansible_default_ipv4.gateway }}
    
    - name: Task for variables
      debug:
        var: inventory_hostname
      
    - name: Task for debug Module verbocity
      debug:
        msg: This is verbocity
        verbosity: 2